config/routes.rb
Rails.application.routes.draw do
	root 'pictures#index'
  devise_for :users
  
  resources :pictures do
  	resources :comments do 
  		resources :scores
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  has_attached_file :image,
                    styles: { large: '1000x1000', medium: '300x300>', thumb: '200x200>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/png']
end

app/models/score.rb
class Score < ApplicationRecord
	belongs_to :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :picture
	has_many :comment	

	validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base

  def create
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comment.create(comment_params)
    @comment.user_id = current_user.id
    @score = Score.new


    redirect_to @picture
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :text)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < InheritedResources::Base

	def create
    @picture = Picture.new(picture_params)

    @picture.user_id = current_user.id

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def average
    @scores = Score.all
    
    count = []
    score = 0
    average = 0

    @scores.each do |key, value| 
      count.push value
    end

    sum_of_scores = count.inject(0) {|result, elem| result + elem}
    average = sum_of_scores.to_f / count.length.to_f
    return average
  end

  private

  	def set_picture
  		@picture = Picture.find(params[:id])
			@picture.image
  	end

    def picture_params
      params.require(:picture).permit(:title, :user_id, :score_id, :image)
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def average
    @scores = Score.all
    
    count = []
    score = 0
    average = 0

    @scores.each do |key, value| 
      count.push value
    end

    sum_of_scores = count.inject(0) {|result, elem| result + elem}
    average = sum_of_scores.to_f / count.length.to_f
    return average
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/comments/_comment.html.erb
<li>
  <p>
    <strong><%= @comment.user.name %></strong> said:
  </p>
  <p>
    <%= @comment.text %>
  </p>
</li>

app/views/comments/_form.html.erb
<%= form_for [@picture, @picture.comment.build] do |f| %>
    <div>
      Text: <%= f.text_area :text %>
    </div>

    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cw6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/application/navbar' %></br>
	
	</br>
	</br>
    <%= yield %>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Notice Board', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
      
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <p class="navbar-text"><%= link_to 'Add Pictures', new_picture_path %></p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div>
    <%= form.file_field :image %>
  </div>
  </br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= image_tag picture.image.url(:thumb) %></td>
        <td><%= link_to picture.title, picture %></td>
        <td><%= picture.user.name %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @picture.user.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @average %>
</p>

<h2>Comments</h2>
<div id="comment-section">
  <ol id="comments">
    <%= render 'comments/comment' %>
  </ol>

  <h3>Add a comment:</h3>
  <%= render 'comments/form' %>
</div>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>